name: Development Build

on:
  push:
    branches:
      - develop
      
jobs:
  verify:
    name: verify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 20
      uses: actions/setup-java@v3.3.0
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven
    - name: Verify with Maven
      run: mvn --batch-mode --update-snapshots verify


  log:
    needs: verify
    name: get the git log for this release
    runs-on: ubuntu-latest
    outputs:
      RELEASE_BODY: ${{ steps.log.outputs.RELEASE_BODY }} # <--- Use environment variable
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: log
        run: |
          message="$(git log --oneline --no-merges development..HEAD)"
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "RELEASE_BODY<<$EOF" >> "$GITHUB_OUTPUT"
          echo "$message" >> "$GITHUB_OUTPUT"
          echo "$EOF" >> "$GITHUB_OUTPUT"
    
  deleteRelease:
    needs: log
    name: delete old development release
    runs-on: ubuntu-latest
    steps:
    - uses: dev-drprasad/delete-tag-and-release@v1.0
      with:
        tag_name: development 
        github_token: ${{ secrets.GITHUB_TOKEN }} 
      
  publish:
    needs: [log, deleteRelease]
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload Application
      # uses: svenstaro/upload-release-action@v2.5 # cant be used now as it does not support other branches than default branch
      uses: Spikatrix/upload-release-action@b713c4b73f0a8ddda515820c124efc6538685492
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        target_commit: develop
        file: test.txt
        prerelease: true
        overwrite: true
        tag: development
        release_name: Automatic Development Build
        body: |
          ${{ needs.log.outputs.RELEASE_BODY }}
