name: Development Build

on:
  push:
    branches:
      - develop
      
jobs:
  deleteRelease:
    name: delete old development Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Delete Release
      uses: larryjoelane/delete-release-action@v1.0.24
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release_name: Automatic Development Build
      
  publish:
    needs: deleteRelease
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload Application
      uses: svenstaro/upload-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: test.txt
        prerelease: true
        overwrite: true
        tag: development
        release_name: Automatic Development Build
        body: This release is an automatic build from the develop branch.