name: Development Build

on:
  push:
    branches:
      - develop
      
jobs:
  log:
    name: get the git log for this release
    shell: bash
    run: |
      r=$(git log --oneline --no-merges development..HEAD)
      echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT          # <--- Set environment variable
    outputs:
      RELEASE_BODY: ${{ steps.log.outputs.RELEASE_BODY }} # <--- Use environment variable
  deleteRelease:
    needs: log
    name: delete old development release
    runs-on: ubuntu-latest
    steps:
    - uses: dev-drprasad/delete-tag-and-release@v1.0
      with:
        tag_name: development 
        github_token: ${{ secrets.GITHUB_TOKEN }} 
      
  publish:
    needs: [log, deleteRelease]
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload Application
      # uses: svenstaro/upload-release-action@v2.5 # cant be used now as it does not support other branches than default branch
      uses: Spikatrix/upload-release-action@b713c4b73f0a8ddda515820c124efc6538685492
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        target_commit: develop
        file: test.txt
        prerelease: true
        overwrite: true
        tag: development
        release_name: Automatic Development Build
        body: |
          ${{ needs.log.outputs.RELEASE_BODY }}  # <--- Use environment variables that was created earlier