name: Development Build

on:
  push:
    branches:
      - develop
      
jobs:
  deleteRelease:
    name: delete old development Release
    runs-on: ubuntu-latest
    steps:
    - uses: dev-drprasad/delete-tag-and-release@v1.0
      with:
        tag_name: development 
        github_token: ${{ secrets.GITHUB_TOKEN }} 
      
  publish:
    needs: deleteRelease
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload Application
      uses: Spikatrix/upload-release-action@b713c4b
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: test.txt
        prerelease: true
        overwrite: true
        tag: development
        release_name: Automatic Development Build
        body: This release is an automatic build from the develop branch.